auto: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
extensions: [smart]
collections:
    Bitcoin:
        output: true
    # Life:
    #     output: true
    Coding:
        output: true