permalink: /:year/:month/:day/:title
extensions: [smart]
collections:
    ForMyDaughters:
        output: true
    Coding:
        output: true
    Bitcoin:
        output: true
    Other:
        output: true