auto: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
extensions: [smart]
collections:
    Life:
        output: true
    Coding:
        output: true
    Bitcoin:
        output: true


